create table person
(
id integer not null,
name varchar(255) not null,
location varchar(255),
birth_date timestamp,
primary key(id)
);

INSERT INTO PERSON(ID,NAME,LOCATION,BIRTH_DATE)
VALUES(1001,'SETHI','GURUGRAM',sysdate());

INSERT INTO PERSON(ID,NAME,LOCATION,BIRTH_DATE)
VALUES(1002,'AMIT','HARYANA',sysdate());

INSERT INTO PERSON(ID,NAME,LOCATION,BIRTH_DATE)
VALUES(1003,'AKSHAY','GUJRAT',sysdate());

INSERT INTO PERSON(ID,NAME,LOCATION,BIRTH_DATE)
VALUES(1004,'AJAY','DELHI',sysdate());


INSERT INTO PERSON(ID,NAME,LOCATION,BIRTH_DATE)
VALUES(1005,'BHARAT','FIROZ',sysdate());